server:
  port: 8081
  maxHttpHeaderSize: 16384
  tomcat:
    uri-encoding: UTF-8


spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

    ## Freemarker 配置
  ## Freemarker 配置
  freemarker:
    charset: UTF-8
    cache: false
    suffix: .ftl
    content-type: text/html
    template-loader-path: classpath:/web/
    check-template-location: true
    expose-session-attributes: true
    expose-request-attributes: true
    request-context-attribute: request

  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    password:

